apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-app
  name: my-app
spec:
  initContainers:
  - name: service-init
    image: ubuntu
    command: ["sh", "-c", "echo waiting for service; sleep 2"]
  - name: db-init
    image: ubuntu
    command: ["sh", "-c", "echo waiting for database; sleep 2"]
  containers:
  - image: nginx
    name: web-app
    resources: {}
    ports:
    - containerPort: 80
    
