---
- name: "install containerd on all nodes"
  hosts: all
  tasks:
  - name: "enable modules"
    ansible.builtin.shell: "sudo modprobe {{ item }}"
    loop: "{{ kernel_modules }}"
  - name: "create modules config"
    ansible.builtin.template:
      src: "{{ templates_dir }}/containerd_modules.j2"
      dest: "{{ kernel_modules_path }}"
  - name: "configure sysctl params"
    ansible.builtin.template:
      src: "{{ templates_dir }}/sysctl_params.j2"
      dest: "{{ sysctl_params_path }}"
...
