apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    apppurpose: lb
    tier: dev
    appversion: v1
  annotations:
    owner: "Anatoliy Kopylov"
    team: "some team"
  name: websrv03
spec:
  containers:
  - image: nginx
    name: websrv03
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}