---
#This playbook will install containerd, kubeadm, kubectl and kubelet, will configure containerd, needed kernel modules and sysctl parameters
#packagess are going to be put on apt hold
#This playbook is idempotent, you can safely run it as many times, as you want
- name: "install containerd, configure modules and sysctl on all nodes"
  hosts: all
  tasks:
  - name: 'disable UFW'
    community.general.ufw:
      state: disabled
  - name: "Add an apt signing key for K8s"
    apt_key:
      url: "{{ kubernetes_gpg_url }}"
      state: present
  - name: "Add apt K8s repository for stable version"
    apt_repository:
      repo: "{{ kubernetes_repo }}"
      state: present
  - name: "install packages"
    apt:
      name: "{{ item.name }}{{ item.version }}"
      state: present
      update_cache: yes
      allow_downgrade: yes
    loop: "{{ common_packages }}"
  - name: "hold installed packages"
    dpkg_selections:
      name: "{{ item.name }}"
      selection: hold
    loop: "{{ common_packages }}"
  - name: "get held packages"
    shell: apt-mark showhold
    register: held_packages
  - name: "show held packages"
    debug:
      msg: "{{ held_packages.stdout_lines }}"
  - name: "enable kubectl autocompletion"
    shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
  - name: "enable kubeadm autocompletion"
    shell: kubeadm completion bash | sudo tee /etc/bash_completion.d/kubeadm > /dev/null
  - name: "create kernel modules auto-load config"
    ansible.builtin.template:
      src: "{{ templates_dir }}/containerd_modules.j2"
      dest: "{{ kernel_modules_path }}"
    notify: "restart systemd-modules-load"
  - name: "configure sysctl params needed by K8s"
    ansible.builtin.template:
      src: "{{ templates_dir }}/sysctl_params.j2"
      dest: "{{ sysctl_params_path }}"
    notify: "apply sysctl"
  - name: "create containerd dir"
    file:
      name: "{{ containerd_dir }}"
      state: directory
  - name: "create containerd config"
    copy:
      src: "{{ templates_dir }}/containerd_conf.toml"
      dest: "{{ containerd_dir }}/{{ containerd_conf }}"
    notify: "restart containerd"
  - name: "make sure the needed services are enabled"
    service:
      name: "{{ item }}"
      enabled: yes
    loop: "{{ common_services }}"
  - name: "create crictl config"
    template:
      src: "{{ templates_dir }}/crictl.j2"
      dest: "/etc/crictl.yaml"
  
  handlers:
  - name: "restart systemd-modules-load"
    service:
      name: systemd-modules-load.service
      state: restarted
  - name: "apply sysctl"
    ansible.builtin.shell: sudo sysctl --system
  - name: "restart containerd"
    service:
      name: containerd.service
      state: restarted 
...
