---
- name: "test"
  hosts: kub_ctrl
  tasks:
  - name: "create configuration files for calico and cluster"
    become: false
    template:
      src: "{{ templates_dir }}/{{ item.template }}"
      dest: "{{ item.file }}"
    loop: "{{ configs }}"
...