- name: "bootstrap cluster"
  hosts: kub_ctrl
  tasks:
  - name: "task1"
    shell: cat asdasd
    register: resultx
  - name: "task2"
    local_action:
      module: copy
      content: "{{ resultx.stdout }}"
      dest: "./kube-init.log"